name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when you push to your 'main' branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant GITHUB_TOKEN the necessary permissions to deploy to GitHub Pages
permissions:
  contents: read
  pages: write # Required for deploying to GitHub Pages
  id-token: write # Required for OIDC authentication

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single deploy job since we're not doing anything more complicated
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version, e.g., '18', '20'

      - name: Install dependencies
        run: npm ci # Uses package-lock.json for consistent installs

      - name: Build Vite App
        # Ensure your vite.config.js base is set to /your-repo-name/
        env:
          # Set the repository name as an environment variable for vite.config.js base path
          # GITHUB_REPOSITORY is automatically available (e.g., 'v8859/CoursePlanner')
          VITE_APP_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: npm run build # Or 'yarn build' if you use Yarn

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
